apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3Jk
  mysql-user: ZGF0YXVzZXI=
  mysql-password: ZGF0YXBhc3M=
  mysql-database: ZGF0YWJhc2U=