apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3Jk # base64 encoded value of 'rootpassword'
  mysql-user: ZGF0YXVzZXI= # base64 encoded value of 'datauser'
  mysql-password: ZGF0YXBhc3M= # base64 encoded value of 'datapass'
  mysql-database: ZGF0YWJhc2U= # base64 encoded value of 'database'